package com.hzitoa.entity;

public class TbDict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.open
     *
     * @mbggenerated
     */
    private String open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dict.checked
     *
     * @mbggenerated
     */
    private String checked;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.id
     *
     * @return the value of tb_dict.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.id
     *
     * @param id the value for tb_dict.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.pid
     *
     * @return the value of tb_dict.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.pid
     *
     * @param pid the value for tb_dict.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.name
     *
     * @return the value of tb_dict.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.name
     *
     * @param name the value for tb_dict.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.open
     *
     * @return the value of tb_dict.open
     *
     * @mbggenerated
     */
    public String getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.open
     *
     * @param open the value for tb_dict.open
     *
     * @mbggenerated
     */
    public void setOpen(String open) {
        this.open = open == null ? null : open.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dict.checked
     *
     * @return the value of tb_dict.checked
     *
     * @mbggenerated
     */
    public String getChecked() {
        return checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dict.checked
     *
     * @param checked the value for tb_dict.checked
     *
     * @mbggenerated
     */
    public void setChecked(String checked) {
        this.checked = checked == null ? null : checked.trim();
    }
}