package com.hzitoa.mapper;

import com.hzitoa.entity.DepartmentInfo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface DepartmentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_info
     *
     * @mbggenerated
     */
    @Delete({
        "delete from department_info",
        "where dept_id = #{deptId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_info
     *
     * @mbggenerated
     */
    @Insert({
        "insert into department_info (dept_id, dept_name, ",
        "pid, company_id, ",
        "create_by, create_date, ",
        "update_by, update_date)",
        "values (#{deptId,jdbcType=INTEGER}, #{deptName,jdbcType=VARCHAR}, ",
        "#{pid,jdbcType=INTEGER}, #{companyId,jdbcType=INTEGER}, ",
        "#{createBy,jdbcType=VARCHAR}, #{createDate,jdbcType=TIMESTAMP}, ",
        "#{updateBy,jdbcType=VARCHAR}, #{updateDate,jdbcType=TIMESTAMP})"
    })
    int insert(DepartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_info
     *
     * @mbggenerated
     */
    int insertSelective(DepartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_info
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "dept_id, dept_name, pid, company_id, create_by, create_date, update_by, update_date",
        "from department_info",
        "where dept_id = #{deptId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    DepartmentInfo selectByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DepartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_info
     *
     * @mbggenerated
     */
    @Update({
        "update department_info",
        "set dept_name = #{deptName,jdbcType=VARCHAR},",
          "pid = #{pid,jdbcType=INTEGER},",
          "company_id = #{companyId,jdbcType=INTEGER},",
          "create_by = #{createBy,jdbcType=VARCHAR},",
          "create_date = #{createDate,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=VARCHAR},",
          "update_date = #{updateDate,jdbcType=TIMESTAMP}",
        "where dept_id = #{deptId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(DepartmentInfo record);
}