package com.hzitoa.mapper;

import com.hzitoa.entity.EmployeeInfo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface EmployeeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated
     */
    @Delete({
        "delete from employee_info",
        "where user_id = #{userId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated
     */
    @Insert({
        "insert into employee_info (user_id, name, ",
        "password, wechat_id, ",
        "dingding_id, email, ",
        "dept_id)",
        "values (#{userId,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{wechatId,jdbcType=VARCHAR}, ",
        "#{dingdingId,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, ",
        "#{deptId,jdbcType=INTEGER})"
    })
    int insert(EmployeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated
     */
    int insertSelective(EmployeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "user_id, name, password, wechat_id, dingding_id, email, dept_id",
        "from employee_info",
        "where user_id = #{userId,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    EmployeeInfo selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EmployeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_info
     *
     * @mbggenerated
     */
    @Update({
        "update employee_info",
        "set name = #{name,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "wechat_id = #{wechatId,jdbcType=VARCHAR},",
          "dingding_id = #{dingdingId,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "dept_id = #{deptId,jdbcType=INTEGER}",
        "where user_id = #{userId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(EmployeeInfo record);
}