package com.hzitoa.mapper;

import com.hzitoa.entity.TbAuthority;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TbAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_authority
     *
     * @mbggenerated
     */
    @Delete({
        "delete from tb_authority",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_authority
     *
     * @mbggenerated
     */
    @Insert({
        "insert into tb_authority (id, name, ",
        "url, pid, available)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{url,jdbcType=VARCHAR}, #{pid,jdbcType=INTEGER}, #{available,jdbcType=TINYINT})"
    })
    int insert(TbAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_authority
     *
     * @mbggenerated
     */
    int insertSelective(TbAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_authority
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, name, url, pid, available",
        "from tb_authority",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    TbAuthority selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_authority
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_authority
     *
     * @mbggenerated
     */
    @Update({
        "update tb_authority",
        "set name = #{name,jdbcType=VARCHAR},",
          "url = #{url,jdbcType=VARCHAR},",
          "pid = #{pid,jdbcType=INTEGER},",
          "available = #{available,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TbAuthority record);
}