package com.hzitoa.mapper;

import com.hzitoa.entity.TbDict;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TbDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbggenerated
     */
    @Delete({
        "delete from tb_dict",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbggenerated
     */
    @Insert({
        "insert into tb_dict (id, pid, ",
        "name, open, checked)",
        "values (#{id,jdbcType=INTEGER}, #{pid,jdbcType=INTEGER}, ",
        "#{name,jdbcType=VARCHAR}, #{open,jdbcType=VARCHAR}, #{checked,jdbcType=VARCHAR})"
    })
    int insert(TbDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbggenerated
     */
    int insertSelective(TbDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, pid, name, open, checked",
        "from tb_dict",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    TbDict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_dict
     *
     * @mbggenerated
     */
    @Update({
        "update tb_dict",
        "set pid = #{pid,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "open = #{open,jdbcType=VARCHAR},",
          "checked = #{checked,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TbDict record);
}